### ISSUE TITLE
There is some bugs in this build please upload a new bug fixed version

### ISSUE THREAD

**Issue by MihinMUD** [TechDudie/TechTest#12]
![image](https://user-images.githubusercontent.com/73010893/101568351-71de5180-39f8-11eb-96bd-46ace1f51b7d.png)

and after fix it I got some other errors so fix it

**Comment by MihinMUD** [comment]
![image](https://user-images.githubusercontent.com/73010893/101570075-a99ac880-39fb-11eb-97e7-b052f305f3c3.png)
this errror too 
look at my fixes in pull requests
after that game loaded but get this errors

**Comment by TechDudie** [comment]
Okay now ill do a code check (not a run as i am busy at the moment), just look and see if i think the code is correct.

**Comment by TechDudie** [comment]
Apparently there are still a few typos, ill push the commits later today.

**Comment by TechDudie** [comment]
Mud, first remove the ‘-main’ suffix to the mod folder.

**Comment by TechDudie** [comment]
Then run it from cmd.exe.

**Comment by MihinMUD** [comment]
how every i did I think error is because some spelling mistakes check all code again
and run it in minetestand see

**Comment by MihinMUD** [comment]
And also I recommend  adding some tools  (aluminum  , Pyrite)
some amour too

**Comment by MihinMUD** [comment]
oh your update worked!!

**Comment by MihinMUD** [comment]
no errors for now i will see

**Comment by TechDudie** [comment]
Okay

**Comment by TechDudie** [comment]
Now, (somehow I dunno) give urself the “give” privilege. Then do
 /give <all_the_items_in_description.txt>.
If the texture says unknown item then there is something wrong with the item registration, if it’s pink and black, the item is registered but there is not texture.

**Comment by TechDudie** [comment]
Try placing the block if it’s a node or eating the item if it’s a food.

**Comment by TechDudie** [comment]
P.S. I just discovered 2 items have missing images, it has to do with gems.lua.

**Comment by MihinMUD** [comment]
Ok

**Comment by MihinMUD** [comment]
I mean the soda bucket it is not eatable or usable

**Comment by MihinMUD** [comment]
![image](https://user-images.githubusercontent.com/73010893/101857940-a126c700-3b8e-11eb-9c3c-6056ceb8ada8.png)
i found this errors 
I will work on it

**Comment by MihinMUD** [comment]
I have send the fixes so I will look for more errors

**Comment by MihinMUD** [comment]
some items has no recipe

**Comment by MihinMUD** [comment]
![image](https://user-images.githubusercontent.com/73010893/101859024-d92f0980-3b90-11eb-9cf4-f7c0ee75cc27.png)
only this items have recipes others don't

**Comment by MihinMUD** [comment]
so tell me if I can make a recipe or you make it

**Comment by MihinMUD** [comment]
Beehive is so bugy


AsyncErr: ServerThread::run Lua: Runtime error from mod 'techtest' in callback item_OnPlace(): "mobs:beehive" is not a registered node!
stack traceback:
	[C]: in function 'set_node'
	...netest-5.3.0-win64\bin\..\mods\TechTest-main/beeswax.lua:24: in function 'after_place_node'
	...-win64\minetest-5.3.0-win64\bin\..\builtin\game\item.lua:385: in function <...-win64\minetest-5.3.0-win64\bin\..\builtin\game\item.lua:258>

game crashed and show this error

**Comment by MihinMUD** [comment]
I know you have to add mob_animal mod as a depended

**Comment by MihinMUD** [comment]
techtest:amethyst
techtest:amethyst_shard
has no inv_images

**Comment by Lanhild** [comment]
Recipes for the following items:

- [ ] techtest:carrot_fruit_snacks

- [ ] techtest:blueberry_fruit_snacks

- [ ] techtest:raspberry_fruit_snacks

- [ ] techtest:hershey5

- [ ] techtest:leather

- [ ] techtest:beeswax

- [ ] techtest:match

Create textures for the following items:

- [ ] amethyst.png

- [ ] amethyst_shard.png

**Comment by TechDudie** [comment]
All the fruit snacks, the match, the leather, and hershey5 should have recipies. Hershey4-0 should not, and beeswax also should not.

**Comment by MihinMUD** [comment]
ok

**Comment by TechDudie** [comment]
Well u both are assigned

**Comment by MihinMUD** [comment]
i just download the mod and run there is no recipe show for  techtest:hershey5

**Comment by MihinMUD** [comment]
i think there is no item call 
farming:chocolate_dark
in farming mod

**Comment by MihinMUD** [comment]
I can work on textures too 
the thing is i don't know what shape is it

**Comment by MihinMUD** [comment]
is it like a Emerald in mc

**Comment by MihinMUD** [comment]
what about soda bucket is it just a craft item? or a food

**Comment by MihinMUD** [comment]
we must have to update depends txt too it very outdated

**Comment by TechDudie** [comment]
Soda is a craft item

**Comment by MihinMUD** [comment]
ok
got it

**Comment by Lanhild** [comment]
> I can work on textures too
> the thing is i don't know what shape is it

I will do textures

**Comment by MihinMUD** [comment]
ok  i only find errors and fix it

**Comment by TechDudie** [comment]
Sure

**Comment by TechDudie** [comment]
The Amethyst Probably should be a triangle shape.

**Comment by TechDudie** [comment]
But first, imma give u collaborator access.

**Comment by MihinMUD** [comment]
I m gonna dwonload the latest version and test it

**Comment by MihinMUD** [comment]
pull request is needed accept quick

**Comment by MihinMUD** [comment]
Gonna close this issue and reopen one for missing textures.
