### ISSUE TITLE
Image Typo

### ISSUE THREAD

**Issue by TechDudie** [TechDudie/TechTest#3]
The mineral_aluminum.png is not names correctly, right now it’s mineral_aluminum.png, and in the code, it references to technic_mineral_aluminum, I would like it changed to mineral_aluminum.png.

**Comment by 96RadhikaJadhav** [comment]
Hi @TechDudie Could you please assign this issue to me so that I can create a PR.

**Comment by TechDudie** [comment]
Sure

**Comment by TechDudie** [comment]
I would like to fix this myself, but I have very limited time.

**Comment by 96RadhikaJadhav** [comment]
Hi @TechDudie  I have created a PR..Could you please review it.

**Comment by TechDudie** [comment]
Okay sure :D

**Comment by TechDudie** [comment]
Done
