### ISSUE TITLE
White Chocolate Peppermint Pretzels

### ISSUE THREAD

**Issue by TechDudie** [TechDudie/TechTest#4]
This falls under the “candy” category, I got the idea when I bought a bag of them, and they were ABSOLUTELY SCRUMPTIOUS! 😋 So it’s very complicated to make, it involves lots of cocoa beans, milk, sugar, red and white dye, mint leaves, flour, water, eggs, salt. (with this I’m adding butter, cocoa powder, cocoa butter, egg wash, pretzels (which are 8 hunger points)). The end result is a pretzel that restores 16 hunger points. I also got part of the idea from Lanhildy’s candy cane suggestion.

**Comment by TechDudie** [comment]
Oops, sorry I assigned the “task” label to the wrong issue.

**Comment by Lanhild** [comment]
item made, just need to add the texture and it's done

**Comment by Lanhild** [comment]
`{"farming:cocoa_beans", "mobs:bucket_milk", "farming:cocoa_beans"},
		{"farming:sugar", "farming:flour", "farming:sugar"},
		{"farming:mint_leaf", "dye:red", "dye:white"},`

Is this recipe too easy?

**Comment by Lanhild** [comment]
Also, made it only restore 12 points, as the golden carrot pretzel will do it 16

**Comment by TechDudie** [comment]
I’m afraid so, it’s very easy, and unrealistic, according to the research I did yesterday.

**Comment by Lanhild** [comment]
I'll make a basic 'naked pretzel' with nothing and then to get the golden one and wchocolate one you have to do another recipe on top of it

**Comment by TechDudie** [comment]
You grind cocoa beans to cocoa powder, craft milk to butter, craft 1 butter and 8 cocoa powder to 1 cocoa butter, then 3 cocoa butter, 5 sugar, and 1 milk to white chocolate. Grind a candy cane to 4 candy cane bits. (Also make sure that you can grind a peppermint candy to 2 peppermint bits.) Craft 1 egg to 1 egg wash. Craft 1 egg wash, 1 bucket of water, and 7 flour to 1 pretzel. Craft white chocolate, a pretzel, and candy cane bits to make these superb pretzels. It’s extremely complicated due to its high nutrition.

**Comment by TechDudie** [comment]
The “naked pretzel” is the regular one, it’s 6 food points (I changed my mind).

**Comment by TechDudie** [comment]
I created pretzel images, but (silly me) I forgot about the golden pretzel. I’ll work on it later.

**Comment by Lanhild** [comment]
oh, I already did the textures

**Comment by TechDudie** [comment]
Okay, your textures are more fancy than mine. The only concern is that the white chocolate pretzel maybe should have the red dots on the entire pretzel, not just the top half. (You can fix this if you want, this isn’t strictly necessary, I don’t mind if you chose not to.)

**Comment by Lanhild** [comment]
fixed
